### ISSUE TITLE
password function in API document missing an argument

### ISSUE THREAD

**Issue by komaruloh** [szkiba/xk6-faker#11]
I found out that [password function document](https://github.com/szkiba/xk6-faker/blob/master/docs/classes/faker.md#password) have different number of parameters from [https://github.com/brianvoe/gofakeit](https://github.com/brianvoe/gofakeit#auth). It seems that the `space` parameter is not documented, but `password()` actually take it as the fifth.

**Comment by szkiba** [comment]
In the meantime, the API has changed, this problem has also been solved in the new API:
https://ivan.szkiba.hu/xk6-faker/interfaces/Internet.html#password
