### ISSUE TITLE
Error running script using xk6-faker

### ISSUE THREAD

**Issue by gabrielzc** [szkiba/xk6-faker#2]
Hi!

I'm trying to execute a script using faker, but I'm receiving this message:

ERRO[0000] unknown module: k6/x/faker
	at reflect.methodValueCall (native)
	at file:///Users/gabrielzc/desktop/k6-script/node_modules/scenarios/usuarios.js:38:121(35)  hint="script exception"

I've imported like the example:

import { Faker } from "k6/x/faker"

let f = new Faker();
console.log(f.name());

Can you help me?

Thanks!

**Comment by Mabciyptyl** [comment]
Hi @gabrielzc 
Make sure you use the k6 compiled by xk6 that in the same directory you build the extension in.

**Comment by szkiba** [comment]
Yes, you need custom k6 build with xk6-faker extension enabled.
